services:
  desktop:
    build: ./images/ubuntu-xfce
    privileged: true
    tty: true
    ports:
      - "45900:5900"
  novnc:
    build: ./images/novnc
    environment:
      VNC_HOST: desktop
    ports:
    - "46080:6080"
