version: "3.3"
volumes:
  desktop-home-developer:
services:
  desktop:
    ports:
    - 15900:5900
    build:
      context: ./
    volumes:
    - desktop-home-developer:/home/developer
  novnc:
    environment:
      VNC_HOST: desktop
    ports:
    - 16080:6080
    build:
      context: ../novnc